spring.application.name=jobportal

security.jwt.expiration=3600000
security.jwt.secret=Af30vSELLXZNACmniZi5prsCSUaAM_i2zqcbQ2rvKtw


spring.datasource.url=jdbc:postgresql://db:5432/jobportal
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
logging.level.root=WARN

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

local.upload.dir=/app/uploads/files